name: Knowrajatmore Firebase CD
 
on:
  push:
    branches: [ main ]

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Firebase Deploy Knowrajatmore
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_AUTH_TOKEN }}'
          projectId: knowrajatmore
          entryPoint: "./"
          channelId: live
